name: Bump main Tag version & create release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:

    # Standard Check of the current git repository
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install and Setup GitVersion version of 5.3.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    # Execute GitVersion against the current repository
    - name: Use GitVersion
      # Step id is used as reference for the output values
      id: gitversion 
      uses: gittools/actions/gitversion/execute@v0.9.7
    # Echo out the version, helps with quick debugging of the build without having to expand the prior step.
    - name: Display GitVersion outputs
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "CommitDate: ${{ steps.gitversion.outputs.commitDate }}"

    # Bump the version as tag
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # We want to tag in our repo the same version we publish to NuGet
        CUSTOM_TAG: ${{ steps.gitversion.outputs.semVer }}
        RELEASE_BRANCHES: main

    # Create the executable
    - name: Create single exe
      run: |
        dotnet publish TirChocoTestApp -c Release -r win-x64 /p:Version=${{ steps.gitversion.outputs.semVer }} /p:PublishSingleFile=true /p:CopyOutputSymbolsToPublishDirectory=false /p:GenerateDocumentationFile=false --self-contained false -o output

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "output/**"
        bodyFile: "CHANGELOG.md"
        tag: ${{ steps.gitversion.outputs.semVer }}
        token: ${{ secrets.GITHUB_TOKEN }}

   # Test Chocolatey
    - name: Choco help
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: -h
