name: CD pipeline

# only trigger deployment when PR om main was closed and merged
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    # Checkout sources. Depth=0 is for using GitVersion
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Setup .NET 6
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    # Install and Setup GitVersion
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    # Execute GitVersion against the current repository
    - name: Use GitVersion
      # Step id is used as reference for the output values
      id: gitversion 
      uses: gittools/actions/gitversion/execute@v0.9.7
    # Echo out the version, helps with quick debugging of the build without having to expand the prior step.
    - name: Display GitVersion outputs
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        echo "CommitDate: ${{ steps.gitversion.outputs.commitDate }}"

    # Call the deploy script
    - name: Deploy
      shell: pwsh
      run: .\tools\deploy.ps1

    # Create Changelog
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        tag-prefix: 'v'
        output-file: CHANGELOG.md
        github-token: ${{ secrets.github_token }}

    # Create GitHub release with created zip-files and CHANGELOG
    #- name: Create release
    #  uses: ncipollo/release-action@v1
    #  with:
    #    artifacts: "output/*.zip"
    #    bodyFile: "RELEASENOTE.md"
    #    tag: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    #    token: ${{ secrets.GITHUB_TOKEN }}
