name: Bump main Tag version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Standard Check of the current git repository
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    # Install and Setup GitVersion version of 5.3.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    # Execute GitVersion against the current repository
    - name: Use GitVersion
      # Step id is used as reference for the output values
      id: gitversion 
      uses: gittools/actions/gitversion/execute@v0.9.7
    # Echo out the version, helps with quick debugging of the build without having to expand the prior step.
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # We want to tag in our repo the same version we publish to NuGet
        CUSTOM_TAG: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
        RELEASE_BRANCHES: main

   # publish artifacts

  # create release

   # publish to chocolatey
