name: CI pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/TirChocoTestApp
    - name: Build
      run: dotnet build src/TirChocoTestApp --no-restore
    - name: Test
      run: dotnet test src/TirChocoTestApp --no-build --verbosity normal
