name: Validate

on:
  push:
    branches: [ develop ]
  pull_request:
<<<<<<< HEAD
    branches: [ main ]
=======
    branches: [ main, develop ]
>>>>>>> ffe26d86f2d647517a6760602d1062d83c322bec

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore TirChocoTestApp
    - name: Build
      run: dotnet build TirChocoTestApp --no-restore
    - name: Test
      run: dotnet test TirChocoTestApp --no-build --verbosity normal
